<?php

/**
 * @file
 * HR Tools Demonstration module.
 *
 * Some parts of this module are based on the Drop Jobs distribution.
 * http://drupal.org/project/drop_jobs
 */
include_once 'hr_tools_demo.features.inc';

/**
 * Implements hook_migrate_api().
 */
function hr_tools_demo_migrate_api() {
  return array(
    'api' => 2,
    'migrations' => array(
      'HrToolsJobTemplate' => array('class_name' => 'HrToolsJobTemplateMigration'),
    ),
  );
}
