<?php
/**
 * @file
 * Code for the HR Tools Search SolR Server feature.
 */

include_once 'hr_tools_search_solr_server.features.inc';

/**
 * Implements hook_default_search_api_index_alter().
 */
function hr_tools_search_solr_server_default_search_api_index_alter(&$configs) {
  // Enable the solr server for the job and resume search.
  $indexes = array('job_index', 'resume_index');
  foreach ($indexes as $index) {
    if (isset($configs[$index])) {
      $configs[$index]->server = "search_solr";
      // Disable the default tokenizer as Solr does a better job.
      $configs[$index]->options['processors']['search_api_tokenizer']['status'] = FALSE;
    }
  }
}
